### PR TITLE
fix sqlite support

### PR DESCRIPTION
**Pull request by ChaosKid42**
I found that this PR is necessary for sqlite support.

### CODE REVIEW

**Comment by madmath03** [comment]
Just saw that this PR is actually partially the same as #44, only difference being the `lib/ejabberd-19.2.0/priv/sql` (not sure why that's necessary though since it's working without it).

**Comment by ChaosKid42** [comment]
`lib/ejabberd-19.2.0/priv/sql` ist necessary in order to allow ejabberd to automatically create the schema. Otherwise it works without it.

**Comment by madmath03** [comment]
Interesting, I did not know ejabberd could create the schema automatically but it's quite nice 😃 

But I think the way you retrieve and store the SQL files is not optimal.
The fact is, you already have the SQL files : it's just in the first stage of the docker build, the `builder` image, so there isn't really a need to download them again.

Look at #42 : this is a PR I sent that copies the SQL from the builder stage and declares them as a generic `VOLUME` (no version in the path) that can be mounted to a DB container like postgres or mysql.

Would ejabberd be able to create the schema if we use a symbolic link to the SQL files ?
If so, would you agree that we "_merge_" your PR with the #42 by adding a symbolic link from `/usr/src/ejabberd/sql` to `$HOME/lib/ejabberd-*/priv/sql` ?

**Comment by ChaosKid42** [comment]
Sorry for late answering:
I'm sure your idea of adding a symbolic link to the directory would work. So I agree to the merge. Do you incorporate the change in your PR? I would close this PR then.

**Comment by madmath03** [comment]
Great.
I think I can do it by the end of the week.

**Pull request closed without merging**
