### PR TITLE
STUN/TURN & SIP

### PR DESCRIPTION
**Pull request by madmath03**
:wrench: Enable STUN/TURN and SIP by default

I would understand if you do not want to add all modules in the docker container, but I was forced to fork the repo just to enable this so I feel like I should at least share the idea 😉

### CODE REVIEW

**Comment by mremond** [comment]
I think this is a good idea to enabled those module in the container. If you want to submit a PR, we will consider it :) Thanks !

**Comment by madmath03** [comment]
Great 😃 
I'm still working on this because, even though I added stun and sip in `vars.config`, I still get an error message :
```
[critical] Listening module ejabberd_stun is not available: ejabberd is not compiled with STUN/TURN support
[critical] Listening module ejabberd_sip is not available: ejabberd is not compiled with SIP support
```

I'm guessing I'm missing something but no idea what... any idea ?

**Comment by madmath03** [comment]
@mremond STUN/TURN and SIP should be ready with this.

I also added the `mod_sip ` to the modules and a sample config for the listeners (did not had the time to test it but it matches the official doc).

**Comment by mremond** [comment]
Thanks, we will have a look 👍

**Comment by cromain** [comment]
This looks good for merge. Thanks.

**Pull request merged**
